__version__:
  serializer: 1
  data: 24
Settings:
  Acquisitions:
    - Acquisition:
        Aperture: 2.18
        Brightness: 1.8
        ExposureTime: 10000
        Gain: 1
  Diagnostics:
    Enabled: no
  Engine: phase
  Processing:
    Color:
      Balance:
        Blue: 1
        Green: 1
        Red: 1
      Experimental:
        Mode: automatic
      Gamma: 1
    Filters:
      Cluster:
        Removal:
          Enabled: yes
          MaxNeighborDistance: 7
          MinArea: 500
      Experimental:
        ContrastDistortion:
          Correction:
            Enabled: yes
            Strength: 0.3
          Removal:
            Enabled: no
            Threshold: 0.3
      Hole:
        Repair:
          Enabled: yes
          HoleSize: 0.2
          Strictness: 2
      Noise:
        Removal:
          Enabled: yes
          Threshold: 3
        Repair:
          Enabled: no
        Suppression:
          Enabled: no
      Outlier:
        Removal:
          Enabled: yes
          Threshold: 20
      Reflection:
        Removal:
          Enabled: yes
          Mode: global
      Smoothing:
        Gaussian:
          Enabled: yes
          Sigma: 4
    Resampling:
      Mode: disabled
  RegionOfInterest:
    Box:
      Enabled: no
      Extents: [-10, 100]
      PointA: [-212.332596, -563.567993, 2241.32178]
      PointB: [348.238586, 263.852478, 2466.79614]
      PointO: [-275.502777, 185.770706, 2022.72498]
    Depth:
      Enabled: yes
      Range: [500, 1300]
  Sampling:
    Color: rgb
    Pixel: all
